# src/main/resources/application.yml
spring:
  kafka:
    bootstrap-servers: localhost:9092

grpc:
  server:
    port: 59091
    enable-reflection: true

kafka:
  topics:
    sensors: telemetry.sensors.v1
    hubs: telemetry.hubs.v1

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.telemetry.collector: INFO
