kafka:
  bootstrap-servers: "localhost:9092"

  snapshots:
    topic: "telemetry.hubs.snapshots.v1"
    group-id: "analyzer-snapshots-group"
    auto-offset-reset: "earliest"
    key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value-deserializer: "ru.yandex.practicum.kafka.serializer.SensorSnapshotDeserializer"

  events:
    topic: "telemetry.hubs.events.v1"
    group-id: "analyzer-events-group"
    auto-offset-reset: "earliest"
    key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value-deserializer: "ru.yandex.practicum.kafka.serializer.HubEventDeserializer"
grpc:
  client:
    hub-router:
      address: 'static://localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


